@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

# @name helth
### Health Check
GET {{host}}/api/health
Content-Type: {{contentType}}

# @name connection
### Add New Device
POST {{host}}/api/connection

###
@deviceId = ""

### Get Device QR Code
{{host}}/api/qr/{{deviceId}}

# @name send-message
### Send Message
POST {{host}}/api/send-message
Content-Type: {{contentType}}

{
    "number": "555199999999",
    "message": "oi",
    "deviceId": "{{deviceId}}"
}